name: Windows CI
on: [push, pull_request]
jobs:
  build:
    name: Windows / ${{ matrix.platform }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, Win32]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $msbuild = & "$vswhere" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1
        $options = @( `
          '-property:Configuration=Release', `
          '-property:Platform=${{ matrix.platform }}', `
          '-maxcpucount', `
          '-verbosity:minimal' `
        )
        & $msbuild Windows\VisualStudio\ironwail.sln $options
        if (-not $?) { throw "Build failed" }
